---
- hosts: 10.10.22.181
  tasks:
    - shell: pwd
      register: abc
    - debug: var=abc
    - git: 
       repo:  https://github.com/Dheerajsilvereye/test/tree/main/git/ip.txt
      register: ab
    - debug: var=ab
