---
- hosts: 10.10.22.181
  tasks:
    - shell: pwd
      register: abc
    - debug: var=abc
    - uri:
       url: https://github.com/Dheerajsilvereye/test/tree/main/git/ip.txt
       return_content: yes
      register: ab
    - debug: var=ab 
      # - git: 
      #      repo:  "cat https://github.com/Dheerajsilvereye/test/tree/main/git/ip.txt"
      #   clone: no
      # register: ab
      #  - debug: var=ab
